// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestAPIExemple.Models;

#nullable disable

namespace RestAPIExemple.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestAPIExemple.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "...",
                            Name = "Bulbasaur",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "...",
                            Name = "Ivysaur",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "...",
                            Name = "Venosaur",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "...",
                            Name = "Charmander",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "...",
                            Name = "Charmeleon",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "...",
                            Name = "Charizard",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "...",
                            Name = "Squirtle",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Description = "...",
                            Name = "Wartortle",
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Description = "...",
                            Name = "Blastoise",
                            Type = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
